### PR TITLE
Add successful script method and yay installation log of heroku-cli

### PR DESCRIPTION
**Pull request by xd003**

### CODE REVIEW

**Comment by SDRausty** [comment]
@xd003 the command used might be well known us today, but a long while from now, should you or I stumble upon this file, will we remember the command being used?  Human readable code is  one of the goals of this project.  Please add the command used to the beginning of the file before `This script requires superuser access.`

- Thank you!

**Review by SDRausty — COMMENTED** [review]
Can also trim the log for clarity please?

**Comment by xd003** [comment]
@SDRausty i have added all relevant instructions inside both the log files . I think ideally we should not trim the log . Reason being firstly the files are nowhere as large as the error logs.
 One of the file is just 80 lines and for the other one being 800 lines , if it was an errror , we could highlight the crucial part before starting of errors .But in a successful installation i think we shouldn't trim anything

**Comment by SDRausty** [comment]
> successful installation 
> we shouldn't trim anything

agreed

**Pull request merged**
